function test1() {
    fail getFailure();
}
