function foo() {
    retry {

     public on fail extra typedesc e {
        io:println("Exception thrown...");
    }
}
