Compiling source
	intg_tests/function_mocking:0.0.0

Running Tests with Coverage

	function_mocking

call_Test3 has failed.


call_Test4 has failed.


call_Test5 has failed.


		Test execution time :*****ms

		[pass] callOriginal_Test1
		[pass] callOriginal_Test2
		[pass] callOriginal_Test3
		[pass] call_Test1
		[pass] call_Test2
		[pass] call_Test6
		[pass] call_Test7
		[pass] call_Test8
		[pass] call_Test9
		[pass] mockErrorResponse
		[pass] mockReplace_Test1
		[pass] mockReplace_Test2
		[pass] thenReturn_Test1
		[pass] withArguments_Test1

		[fail] call_Test3:

		    error {ballerina/test:0}FunctionSignatureMismatchError ("Mock function 'invalidMockFunction' cannot be found")
				callableName: mockHandler moduleName: ballerina.test.0 fileName: mock.bal lineNumber: 383
				callableName: call_Test3 moduleName: intg_tests.function_mocking$test.0.tests.main_test fileName: tests/main_test.bal lineNumber: 164
				callableName: call_Test3$lambda2$ moduleName: intg_tests.function_mocking$test.0.tests.test_execute-generated_*****lineNumber: 6
			

		[fail] call_Test4:

		    error {ballerina/test:0}FunctionSignatureMismatchError ("Return type of function mockIntAdd3 does not match function intAdd")
				callableName: mockHandler moduleName: ballerina.test.0 fileName: mock.bal lineNumber: 383
				callableName: call_Test4 moduleName: intg_tests.function_mocking$test.0.tests.main_test fileName: tests/main_test.bal lineNumber: 170
				callableName: call_Test4$lambda3$ moduleName: intg_tests.function_mocking$test.0.tests.test_execute-generated_*****lineNumber: 7
			

		[fail] call_Test5:

		    error {ballerina/test:0}FunctionSignatureMismatchError ("Parameter types of function mockIntAdd4 does not match function intAdd")
				callableName: mockHandler moduleName: ballerina.test.0 fileName: mock.bal lineNumber: 383
				callableName: call_Test5 moduleName: intg_tests.function_mocking$test.0.tests.main_test fileName: tests/main_test.bal lineNumber: 176
				callableName: call_Test5$lambda4$ moduleName: intg_tests.function_mocking$test.0.tests.test_execute-generated_*****lineNumber: 8
			


		14 passing
		3 failing
		0 skipped

	function_mocking.mock2

		Test execution time :*****ms

		[pass] test1
		[pass] test2
		[pass] test3


		3 passing
		0 failing
		0 skipped

Generating Test Report
	function-mocking-tests/target/report/test_results.json

error: there are test failures